### ISSUE TITLE
[1.16.5] DUPE - Breaking Sea Lanterns with the obsidian Glass cutter gives double output.

### ISSUE THREAD

**Issue by ProsperCraft** [MrCrayfish/GlassCutter#21]
You get the complete sea lantern, and prismarine shards as well.

glasscutter-1.16.4-2.0.1

Modpack - [TownCraft TWO for 1.16.5](https://www.curseforge.com/minecraft/modpacks/towncraft)

**Comment by MrCrayfish** [comment]
This mod is not even in that modpack... and this glass cutter can only cut glass.
