### ISSUE TITLE
Forget in the mod

### ISSUE THREAD

**Issue by Nordery** [MrCrayfish/GlassCutter#4]
We can't recover the Glass Cutter when we broken it differently from stone cutter that we can recover with a wood pickaxe.

**Comment by MrCrayfish** [comment]
Fixed. Download the latest update

**Comment by Nordery** [comment]
Thank you very much MrCrayfish ^^
I'm sorry for the spelling mistakes because I'm French and I've a suggestion :
The Glass could relate their textures with Glass, Glass Stair and Glass Slab with Optifine Mod
