### ISSUE TITLE
Sort Blocks in Creative Tab / JEI

### ISSUE THREAD

**Issue by TheDirectorX** [MrCrayfish/GlassCutter#6]
It is inconvenient that the blocks are arranged in a chaotic order.
![2020-03-15_03 04 25](https://user-images.githubusercontent.com/43481085/76691154-cc18d480-6669-11ea-871f-9d1fec018f6b.png)

**Comment by MrCrayfish** [comment]
Creative tabs are sorted by id. Modded blocks and items are dynamically assigned an ID per world. There is no guarantee of the order, espeically if mods have been removed, ids become free and other mods will fill those.
